config/routes.rb
Rails.application.routes.draw do
  
  get 'static/home'
  #get 'sessions/new'
  #get 'session/new'
  #get 'session/create'
  #get 'session/destroy'
  #get 'comment/new'
  #get 'comment/show'
  #get 'comment/edit'
  #get 'gossips/edit'
  get 'cities/index'
  get 'welcome/:first_name', to: 'welcome#welcome'
  get 'contact', to:'static#contact'
  get 'team', to: 'static#team'
  resources :gossips
  resources :sessions, only: [:new, :create, :destroy]
  resources :users 
  resources :cities
  resources :comments 
  resources :gossips do
    resources :comments
  end
  root 'static#home'
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    validates :name,
    presence: true
    has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :commentable, polymorphic: true
    has_many :likes, :as => :likeable, dependent: :destroy
    has_many :comments, :as => :commentable, dependent: :destroy
    


  end

app/models/gossip.rb
class Gossip < ApplicationRecord
    validates :title,
    presence: true,
    length: { in: 3..14 }
    validates :content,
    presence: true
    belongs_to :user
    has_many :comments, :as => :commentable, dependent: :destroy
    has_many :jointure_gossips 
    has_many :tags, through: :jointure_gossips
    has_many :likes, :as => :likeable, dependent: :destroy
  end

app/models/jointure_gossip.rb
class JointureGossip < ApplicationRecord
    belongs_to :tag
    belongs_to :gossip
end

app/models/jointure_message.rb
class JointureMessage < ApplicationRecord
    belongs_to :recipient, class_name: "User"
    belongs_to :private_message
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :likeable, polymorphic: true
    belongs_to :user
  end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
    belongs_to :sender, class_name: "User"
    has_many :jointure_messages
    has_many :recipients, class_name: "User", through: :jointure_messages
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :jointure_gossips
    has_many :gossips, through: :jointure_gossips
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :password, presence: true, length: {minimum: 6}
    
    #validates :first_name, 
    #presence: true
    #validates :last_name,
    #presence: true
    validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
    belongs_to :city, optional: true
    has_many :gossips
    has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
    has_many :jointure_messages
    has_many :received_messages, foreign_key: 'recipient_id', class_name: "JointureMessage"
    has_many :likes
    has_many :comments
   
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :authenticate_user, only: [:index]
  def index
    @city = City.all
  end
  def show
    @city = City.find(params[:id])
    
  end
end

app/controllers/comment_controller.rb
class CommentsController < ApplicationController
  #before_action :authenticate_user, only: [:new, :create]
    def new
      @comment = Comment.new
      @gossip = Gossip.find(params[:gossip_id])
  
      puts "n" * 100
    end
  
    def create
      @gossip = Gossip.find(params[:gossip_id])
      puts "c" * 100
      # @gossip = Gossip.create(:user => User.all.sample, :title => params[:title], :content => params[:content])
      # redirect_to root_path
        #@comment = Comment.new(:user_id => User.all.sample, :commentable_type => "Gossip", :commentable_id => params[:gossip_id], :content => params[:content]) # avec xxx qui sont les données obtenues à partir du formulaire
        @comment = Comment.new(:user => User.all.sample, :commentable => @gossip, :content => params[:content])
        if @comment.save # essaie de sauvegarder en base @gossip
          redirect_to gossip_path(@gossip.id) # si ça marche, il redirige vers la page d'index du site
        else
          # sinon, il render la view new (qui est celle sur laquelle on est déjà)
          render new_gossip_path
        end
    end
  
    def edit
      @comment = Comment.find(params[:id])
      @gossip = Gossip.find(params[:gossip_id])
  
    end
  
  def update
    puts "$" * 100
    puts @gossip
    puts "$" * 100
    @comment = Comment.find(params[:id])
    comment_params = params.require(:comment).permit(:content)
     if @comment.update(comment_params)
        redirect_to root_path
    else
        render :edit
    end
    # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
    # pour info, le contenu de ce formulaire sera accessible dans le hash params
    # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)
  end
  end
  

app/controllers/like_controller.rb
class LikeController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   
  def show
    @user= User.find(params[:id])
  end

  def new
    @user = User.new 
  end
  def create
    puts params
        @user = User.new(user_params)
        @user.city_id = City.all.sample.id
        if @user.save
            flash[:notice] = "Création réussie"
            redirect_to gossips_path

        else
            render new_user_path  
        end 
  end

    private
    
  def user_params
        params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        User.find_by(id: session[:user_id])
    end

    def log_in(user)
        session[:user_id] = user.id
        
    end
    def logged_in?
        if log_in
            true
        else
            false
        end
    end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/comment/show.html.erb
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
  <h1 class="display-4">View Gossip</h1>
  <p class="lead">Here's a juicy gossip for you. Enjoy!</p>
</div>

<br>

<div class="container">
<div class="card">
  <h5 class="card-header">
    <a <%= link_to "#{@gossip.user.first_name}", user_path(@gossip.user.id) %> • <%= link_to "#{@gossip.user.city.name}", city_path(@gossip.user.city.id) %> </a>
  </h5>
    <div class="card-body">
      <h5 class="card-title"><%= @gossip.title %> </h5>
      <p class="card-text"><%= @gossip.content %></p>
      <a <%= link_to "Edit", edit_gossip_path(@gossip.id), :class => "btn btn-outline-primary" %> </a>
      <a <%= link_to "Delete", gossip_path(@gossip.id), :class => "btn btn-outline-danger", :method => :delete%> </a>
      <a <%= link_to "Comment", new_gossip_comment_path(@gossip.id), :class => "btn btn-outline-primary" %> </a>


    </div>
  </div>
</div>
</div>

<br>

<div class="container">
  <div class="row">
    <div class="col-sm-8">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">Add a Comment</h5>
          <%= form_tag gossip_comments_path do %>
          <div class="form-group">
            <%= text_area_tag :content, placeholder = "Add a comment here...", class: 'form-control no-border' %>
          </div>
            <%= submit_tag "Comment", class: 'btn btn-default btn btn-primary' %>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<br>

<div class="container">
  <div class="container">
  <% @gossip.comments.each do |n| %>
  <div class="media">
    <!-- <%= image_tag "user.png", :size => "20x20" %> -->
    <div class="media-body">
      <h5 class="mt-0"><%= n.user.first_name %></h5>
      <%= n.content %>
    </div>
  </div> <br>
  <% end %>
</div>
</div>