config/routes.rb
Rails.application.routes.draw do
  
  get 'static/home'
  #get 'sessions/new'
  #get 'session/new'
  #get 'session/create'
  #get 'session/destroy'
  #get 'comment/new'
  #get 'comment/show'
  #get 'comment/edit'
  #get 'gossips/edit'
  get 'cities/index'
  get 'welcome/:first_name', to: 'welcome#welcome'
  get 'contact', to:'static#contact'
  get 'team', to: 'static#team'
  resources :gossips
  resources :sessions, only: [:new, :create, :destroy]
  resources :users 
  resources :cities
  resources :comments 
  resources :gossips do
    resources :comments
  end
  root 'static#home'
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    validates :name,
    presence: true
    has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :commentable, polymorphic: true
    has_many :likes, :as => :likeable, dependent: :destroy
    has_many :comments, :as => :commentable, dependent: :destroy
    


  end

app/models/gossip.rb
class Gossip < ApplicationRecord
    validates :title,
    presence: true,
    length: { in: 3..14 }
    validates :content,
    presence: true
    belongs_to :user
    has_many :comments, :as => :commentable, dependent: :destroy
    has_many :jointure_gossips 
    has_many :tags, through: :jointure_gossips
    has_many :likes, :as => :likeable, dependent: :destroy
  end

app/models/jointure_gossip.rb
class JointureGossip < ApplicationRecord
    belongs_to :tag
    belongs_to :gossip
end

app/models/jointure_message.rb
class JointureMessage < ApplicationRecord
    belongs_to :recipient, class_name: "User"
    belongs_to :private_message
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :likeable, polymorphic: true
    belongs_to :user
  end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
    belongs_to :sender, class_name: "User"
    has_many :jointure_messages
    has_many :recipients, class_name: "User", through: :jointure_messages
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :jointure_gossips
    has_many :gossips, through: :jointure_gossips
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :password, presence: true, length: {minimum: 6}
    
    #validates :first_name, 
    #presence: true
    #validates :last_name,
    #presence: true
    validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
    belongs_to :city, optional: true
    has_many :gossips
    has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
    has_many :jointure_messages
    has_many :received_messages, foreign_key: 'recipient_id', class_name: "JointureMessage"
    has_many :likes
    has_many :comments
   
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  before_action :authenticate_user, only: [:index]
  def index
    @city = City.all
  end
  def show
    @city = City.find(params[:id])
    
  end
end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController
    #before_action :authenticate_user, only: [:new, :create]
    
    include SessionsHelper
    
    
    def index
        @gossips = Gossip.all
        # Méthode qui récupère tous les potins et les envoie à la view index (index.html.erb) pour affichage
    end
    
    def show
        @gossips = Gossip.find(params[:id])
        @comment = Comment.new
        # Méthode qui récupère le potin concerné et l'envoie à la view show (show.html.erb) pour affichage
    end
    
    def new
        @gossip = Gossip.new
        # Méthode qui crée un potin vide et l'envoie à une view qui affiche le formulaire pour 'le remplir' (new.html.erb)
    end
    def create
        @gossip = Gossip.new(content: (params[:content]), title: (params[:title]), User.find_by(id: session[:user_id]) )
      
        if @gossip.save
          flash[:success] = "Potin bien créé !"
          redirect_to gossips_path
        else
          render :new
          #render "new"
        end
    end
   
    def edit
        @gossips = Gossip.find(params[:id])
        # Méthode qui récupère le potin concerné et l'envoie à la view edit (edit.html.erb) pour affichage dans un formulaire d'édition
    end
    
    def update
        @gossips = Gossip.find(params[:id])
        gossips_params = params.require(:gossip).permit(:title, :content)
        if @gossips.update(gossips_params)
            redirect_to gossips_path
        else
            render :edit
        end
        # Méthode qui met à jour le potin à partir du contenu du formulaire de edit.html.erb, soumis par l'utilisateur
        # pour info, le contenu de ce formulaire sera accessible dans le hash params
        # Une fois la modification faite, on redirige généralement vers la méthode show (pour afficher le potin modifié)
    end
    
    def destroy
        @gossips = Gossip.find(params[:id])
        @gossips.destroy
        redirect_to gossips_path
        # Méthode qui récupère le potin concerné et le détruit en base
        # Une fois la suppression faite, on redirige généralement vers la méthode index (pour afficher la liste à jour)
    end


end

app/controllers/like_controller.rb
class LikeController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   
  def show
    @user= User.find(params[:id])
  end

  def new
    @user = User.new 
  end
  def create
    puts params
        @user = User.new(user_params)
        @user.city_id = City.all.sample.id
        if @user.save
            flash[:notice] = "Création réussie"
            redirect_to gossips_path

        else
            render new_user_path  
        end 
  end

    private
    
  def user_params
        params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        User.find_by(id: session[:user_id])
    end

    def log_in(user)
        session[:user_id] = user.id
        
    end
    def logged_in?
        if log_in
            true
        else
            false
        end
    end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/gossips/edit.html.erb
<h1>Gossips#edit</h1>
<%= form_for @gossips do |f| %>
  <div class="form-group">
    <label>Titre </label>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label>Contenu</label>
    <%= f.text_area :content, class: 'form-control' %>
  </div>
  <div class="form-group">
    <button type="submit"class="btn btn-primary">Modifier l'article</button>
  </div>

<% end %>

app/views/gossips/index.html.erb
<div class="jumbotron jumbotron-fluid">
<div class="container justify-text-center">
  <h1 class="display-4 text-white">Bienvenue dans The Gossip Project</h1>
  <p class="lead text-white text-uppercase badge badge-primary text-wrap" style="width: 20rem;">liste de tous les gossips.</p>
</div>
</div>


<center><div class="list-group justify-content">
<% @gossips.each do |gossip| %>
<div class="card w-75">
  <h5 class=""><%= gossip.user.first_name%></h5>
  <h6 class="card-subtitle text-muted"><%= gossip.title%></h6>
  <p class="card-text "><%= gossip.content%></p>
  <a href="<%= gossip_path(gossip.id)%>" class="card-link btn btn-primary btn-sm">Consulter</a>
  <a href="<%= edit_gossip_path(gossip.id)%>" class="card-link btn btn-primary btn-sm">Editer</a>
  <a href="<%= user_path(gossip.user.id)%>" class="card-link btn btn-primary btn-sm">Auteur</a>
  <a href="<%= gossip_path(gossip.id)%>" class="btn btn-danger btn-sm" data-confirm= "êtes vous sûr?" data-method="DELETE" >Supprimer</a>
  </div>

</div>
<br>

<%end%>

app/views/gossips/new.html.erb
<h1>Création d'un Gossip</h1>
<%= form_tag(gossips_path, method: "post") do %>
    <%= label_tag( "Prénom") %>
    <%= text_field_tag(:first_name) %>
    <%= label_tag( "Nom") %>
    <%= text_field_tag(:last_name) %>
    <%= label_tag( "Title") %>
    <%= text_field_tag(:title) %>
    <%= text_area_tag(:content, "Tape ton gossip ici", size: "24x6") %>
    
    <%= submit_tag("Validates") %>
<% end %>

app/views/gossips/show.html.erb
<div class="card text-center">
  <div class="card-body">
    <h5 class="card-title"><%= @gossips.title %></h5>
    <p class="card-text"><%= @gossips.content %></p>
    <footer class="blockquote-footer"><%= @gossips.user.first_name %>
    <br>
    <%= @gossips.user.city.name %></footer>
    <% @gossips.comments.each do |comment| %>
      <p>les commentaires: <%= comment.content%></p>
    <%end%>

    <%= link_to "Profil", user_path(@gossips.user.id), :class=>"btn btn-primary" %> 
  </div>
</div>