config/routes.rb
Rails.application.routes.draw do
  
  get 'static/home'
  #get 'sessions/new'
  #get 'session/new'
  #get 'session/create'
  #get 'session/destroy'
  #get 'comment/new'
  #get 'comment/show'
  #get 'comment/edit'
  #get 'gossips/edit'
  get 'cities/index'
  get 'welcome/:first_name', to: 'welcome#welcome'
  get 'contact', to:'static#contact'
  get 'team', to: 'static#team'
  resources :gossips
  resources :sessions, only: [:new, :create, :destroy]
  resources :users 
  resources :cities
  resources :comments 
  resources :gossips do
    resources :comments
  end
  root 'static#home'
 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    validates :name,
    presence: true
    has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :user
    belongs_to :commentable, polymorphic: true
    has_many :likes, :as => :likeable, dependent: :destroy
    has_many :comments, :as => :commentable, dependent: :destroy
    


  end

app/models/gossip.rb
class Gossip < ApplicationRecord
    validates :title,
    presence: true,
    length: { in: 3..14 }
    validates :content,
    presence: true
    belongs_to :user
    has_many :comments, :as => :commentable, dependent: :destroy
    has_many :jointure_gossips 
    has_many :tags, through: :jointure_gossips
    has_many :likes, :as => :likeable, dependent: :destroy
  end

app/models/jointure_gossip.rb
class JointureGossip < ApplicationRecord
    belongs_to :tag
    belongs_to :gossip
end

app/models/jointure_message.rb
class JointureMessage < ApplicationRecord
    belongs_to :recipient, class_name: "User"
    belongs_to :private_message
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :likeable, polymorphic: true
    belongs_to :user
  end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
    belongs_to :sender, class_name: "User"
    has_many :jointure_messages
    has_many :recipients, class_name: "User", through: :jointure_messages
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :jointure_gossips
    has_many :gossips, through: :jointure_gossips
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :password, presence: true, length: {minimum: 6}
    
    #validates :first_name, 
    #presence: true
    #validates :last_name,
    #presence: true
    validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
    belongs_to :city, optional: true
    has_many :gossips
    has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
    has_many :jointure_messages
    has_many :received_messages, foreign_key: 'recipient_id', class_name: "JointureMessage"
    has_many :likes
    has_many :comments
   
end

app/controllers/like_controller.rb
class LikeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        User.find_by(id: session[:user_id])
    end

    def log_in(user)
        session[:user_id] = user.id
        
    end
    def logged_in?
        if log_in
            true
        else
            false
        end
    end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Thegossipproject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>
  <header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="#">TheGossipProject</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", gossips_path, :class=>"nav-link"  %>
      </li>
      <li class="nav-item">
         <%= link_to "Create", new_gossip_path, :class=>"nav-link"  %>
      </li>
      <li class="nav-item">
        <%= link_to "Team", team_path, :class=>"nav-link"  %>
      </li>
      <li class="nav-item">
         <%= link_to "Contact", contact_path, :class=>"nav-link"  %>
      </li>
      <li class="nav-item">
         <%= link_to "s'inscrire", new_user_path, :class=>"nav-link"  %>
      </li>
      <li class="nav-item">
         <%= link_to "se connecter", new_session_path, :class=>"nav-link"  %>
      </li>
         <li class="nav-item">
         <%= link_to "se déconnecter", session_path(session.id), method: :delete, :class=>"nav-link"  %>
      </li>
      
    </ul>
     
  </div>
</nav>
  </header>
  <body>
    <%= yield %>
  </body>
</html>